# Generated by Django 3.1.6 on 2021-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210326_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.URLField(max_length=100),
        ),
    ]
