# Generated by Django 3.1.6 on 2021-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210408_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('valid', models.BooleanField(blank=True, default=False)),
                ('rank', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
