# Generated by Django 3.1.6 on 2021-03-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_artC', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('entry', models.TextField()),
            ],
        ),
    ]
