# Generated by Django 3.1.6 on 2021-03-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-published_date']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='entry',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='published_date',
        ),
    ]
